import turtle
a=turtle.Turtle()
a.speed(5)
a.color("yellow")
a.pencolor("black")
a.begin_fill()
a.circle(150)
a.end_fill()
a.penup()
a.setpos(50,170)
a.pendown()
a.color("black")
a.begin_fill()
a.circle(20)
a.end_fill()
a.penup()
a.setpos(-50,170)
a.pendown()
a.color("black")
a.begin_fill()
a.circle(20)
a.end_fill()
a.penup()
a.setpos(-45,50)
a.pendown()
a.pensize(10)
a.right(45)
a.forward(1)
for i in range(100):
    a.forward(1)
    a.left(1)

turtle.done()